language: node_js
node_js:
  - '6'
  - '8'
  - 'lts/*'
  - 'node'

matrix:
  include:
    - node_js: '4'
      env: NO_LINT=true

script:
  - if [[ -z "${NO_LINT}" ]]; then npm run lint; fi
  - npm test
